export const menuItems = [
  {
    id: 'sindhi-biryani',
    name: 'Sindhi Chicken Biryani',
    category: 'Rice & Tandoor',
    description: 'Fragrant rice, tender chicken, potatoes, mint and house raita.',
    price: 780,
    image: '/images/menu/sindhi-biryani.jpg',
    featured: true,
    spice: 'Medium',
  },
  {
    id: 'chicken-karahi',
    name: 'Dera Chicken Karahi',
    category: 'Karahi',
    description: 'Tomato, ginger, green chilli and fresh coriander, cooked to order.',
    price: 1850,
    image: '/images/menu/chicken-karahi.jpg',
    featured: true,
    spice: 'Hot',
  },
  {
    id: 'seekh-kebab',
    name: 'Charcoal Seekh Kebab',
    category: 'BBQ',
    description: 'Hand-pressed beef kebabs, smoked over charcoal with mint chutney.',
    price: 990,
    image: '/images/menu/seekh-kebab.jpg',
    featured: true,
    spice: 'Medium',
  },
  {
    id: 'mutton-karahi',
    name: 'Namkeen Mutton Karahi',
    category: 'Karahi',
    description: 'Slow-cooked mutton with black pepper, garlic and mountain salt.',
    price: 3200,
    image: '/images/menu/mutton-karahi.jpg',
    spice: 'Mild',
  },
  {
    id: 'chicken-biryani',
    name: 'Matka Chicken Biryani',
    category: 'Rice & Tandoor',
    description: 'Aromatic rice sealed in a clay pot with saffron and fried onion.',
    price: 890,
    image: '/images/menu/chicken-biryani.jpg',
    spice: 'Medium',
  },
  {
    id: 'tandoori-chai',
    name: 'Tandoori Chai',
    category: 'Beverages',
    description: 'Cardamom tea finished in a hot clay cup for a deep smoky aroma.',
    price: 320,
    image: '/images/menu/tandoori-chai.jpg',
    spice: 'None',
  },
  {
    id: 'mango-lassi',
    name: 'Mango Lassi',
    category: 'Beverages',
    description: 'Thick yogurt, ripe mango and pistachio served ice cold.',
    price: 390,
    image: '/images/menu/mango-lassi.jpg',
    spice: 'None',
  },
  {
    id: 'gajjar-halwa',
    name: 'Gajjar Halwa',
    category: 'Desserts',
    description: 'Slow-cooked carrot, khoya, cardamom and roasted nuts.',
    price: 450,
    image: '/images/menu/gajjar-halwa.jpg',
    spice: 'None',
  },
];
